# Generated by Django 3.1.4 on 2020-12-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
    ]
