# Generated by Django 3.1.4 on 2020-12-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Worn')),
                ('mood', models.CharField(choices=[('A', 'fabulous!'), ('B', 'okay'), ('C', 'not great...')], default='A', max_length=1)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.style')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
