# Generated by Django 3.1.4 on 2020-12-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_style_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
    ]
