# Generated by Django 3.1.4 on 2020-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory_wearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
