# Generated by Django 3.1.4 on 2020-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_style_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.TextField(max_length=200),
        ),
    ]
