# Generated by Django 3.1.4 on 2020-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_style_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='date',
            field=models.DateField(verbose_name='wearing date'),
        ),
    ]
