# Generated by Django 3.1.4 on 2020-12-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201218_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
    ]
